spring:
  profiles:
    active: sample-data,dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: smart0asss@gmail.com
    password: xktgqymujlzkwtce
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            thrust: smtp.gmail.com
          starttls:
            required: true
            enabled: true
user:
  registration:
    account-already-activated-url: 'http://localhost:4200/already-activated'
    activation-failed-url: 'http://localhost:4200/activation-failed'
    activation-success-url: 'http://localhost:4200/activation-successful'
    activation-link-template: 'http://localhost:8080/api/user-management/activate?activationId=%s'
admin:
  user:
    password: 'admin'
    username: 'admin@devplant.ro'

