version: '2'
services:

  library-webapp:
    image: devplant/library-webapp
    restart: always
    links:
      - library-backend
    ports:
      - 8080:80
    environment:
      - VIRTUAL_HOST=*
      - VIRTUAL_HOST_WEIGHT=0

  library-backend:
    image: devplant/library-backend
    restart: always
    ports:
      - 7000:7000
    environment:
      - VIRTUAL_HOST=*/api/*
      - VIRTUAL_HOST_WEIGHT=1

  proxy:
    image: dockercloud/haproxy
    links:
      - library-backend
      - library-webapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80