version: '2'
services:

  spring-basics-webapp:
    image: devplant/spring-basics-webapp
    restart: always
    links:
      - spring-basics-backend
    ports:
      - 8080:80
    environment:
      - VIRTUAL_HOST=*
      - VIRTUAL_HOST_WEIGHT=0

  spring-basics-backend:
    image: devplant/spring-basics-backend
    restart: always
    ports:
      - 7000:7000
    environment:
      - VIRTUAL_HOST=*/api/*
      - VIRTUAL_HOST_WEIGHT=1

  proxy:
    image: dockercloud/haproxy
    links:
      - spring-basics-webapp
      - spring-basics-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80